import MAP from "../data/hero-widths.json";

/**
 * A hero is the LCP element on every page and was being sent at full desktop
 * width to phones. public/Images carries -640w/-1024w variants generated by
 * scripts/responsive-images.py; this turns a hero path into the srcset that
 * uses them. Returns undefined when an image has no variants, so the caller
 * falls back to plain src.
 */
export function heroSrcset(src: string): string | undefined {
  const entry = (MAP as Record<string, { variants: number[]; width: number }>)[src];
  if (!entry) return undefined;
  const parts = entry.variants.map((w) => `${src.replace(/\.webp$/, `-${w}w.webp`)} ${w}w`);
  parts.push(`${src} ${entry.width}w`);
  return parts.join(", ");
}
